namespace Promact.Erp.Util.StringLiteral
{
    public class AppStringLiteral
    {
        public string EmailSubject { get; set; }
        public string FromDate { get; set; }
        public string EndDate { get; set; }
        public string Reason { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string ReJoinDate { get; set; }
        public string CreatedOn { get; set; }
        public string WebRequestContentType { get; set; }
        public string DateFormat { get; set; }
        public string ResponseTypeEphemeral { get; set; }
        public string Approved { get; set; }
        public string Button { get; set; }
        public string Rejected { get; set; }
        public string Fallback { get; set; }
        public string Color { get; set; }
        public string AttachmentType { get; set; }
        public string CancelLeaveError { get; set; }
        public string SlackHelpMessage { get; set; }
        public string SlackErrorMessage { get; set; }
        public string Link { get; set; }
        public string Unlink { get; set; }
        public string NotActiveUser { get; set; }
        public string NotTeamLeader { get; set; }
        public string ListOfLinks { get; set; }
        public string ProjectAndTeamLeaderDetail { get; set; }
        public string ProjectTeamLeaderDetail { get; set; }
        public string ProjectLinked { get; set; }
        public string UnLinkFirst { get; set; }
        public string InActiveProject { get; set; }
        public string AlreadyLinked { get; set; }
        public string NotLinkedYet { get; set; }
        public string UnlinkedSuccessfully { get; set; }
        public string NotLinkedToChannel { get; set; }
        public string NoLinks { get; set; }
        public string Links { get; set; }
        public string NotTeamLeaderOfProject { get; set; }
        public string UsersDetailByChannelNameUrl { get; set; }
        public string UserDetailsByIdUrl { get; set; }
        public string UrlRtmStart { get; set; }
        public string OAuthAuthorizationScopeAndClientId { get; set; }
        public string UserDetailsUrl { get; set; }
        public string TeamLeaderDetailsUrl { get; set; }
        public string ManagementDetailsUrl { get; set; }
        public string OAuthAcessUrl { get; set; }
        public string SlackAuthorize { get; set; }
        public string UserCouldNotBeAdded { get; set; }
        public string ProjectDetailsByUserNameUrl { get; set; }
        public string ProjectDetailUrl { get; set; }
        public string ProjectUsersByTeamLeaderId { get; set; }
        public string ProjectUserDetailsUrl { get; set; }
        public string ProjectTeamLeaderDetailsUrl { get; set; }
        public string ProjectManagementDetailsUrl { get; set; }
        public string UserDetailUrl { get; set; }
        public string ThankYou { get; set; }
        public string InternalError { get; set; }
        public string SlackUserListUrl { get; set; }
        public string ProjectDetailsFromOauthInValidUser { get; set; }
        public string ProjectDetailsFromOauthOneEmployee { get; set; }
        public string ProjectDetailsFromOauthOneInActiveEmployee { get; set; }

        public string ProjectDetailsFromOauthThreeEmployeeInActive { get; set; }
        public string ProjectDetailsFromOauthThreeEmployee { get; set; }
        public string ProjectChannelNotLinked { get; set; }

        public string SlackChannelListUrl { get; set; }
        public string SlackGroupListUrl { get; set; }
        public string TaskMailBotStatusErrorMessage { get; set; }
        public string TaskMailBotHourErrorMessage { get; set; }
        public string TaskMailDescription { get; set; }
        public string TaskMailHours { get; set; }
        public string TaskMailComment { get; set; }
        public string TaskMailStatus { get; set; }
        public string StartBot { get; set; }
        public string ScrumHalt { get; set; }
        public string ScrumHalted { get; set; }
        public string ScrumAlreadyHalted { get; set; }
        public string ScrumResume { get; set; }
        public string Scrum { get; set; }
        public string ScrumResumed { get; set; }
        public string AnswerToday { get; set; }
        public string ScrumNotHalted { get; set; }
        public string ScrumHelp { get; set; }
        public string ScrumHelpMessage { get; set; }
        public string NotAUser { get; set; }
        public string NotAProject { get; set; }
        public string Leave { get; set; }
        public string Later { get; set; }
        public string LeaveError { get; set; }
        public string ResumeScrum { get; set; }
        public string SlackAppAdded { get; set; }
        public string SlackAuthError { get; set; }
        public string SlackAppError { get; set; }
        public string LoggerErrorMessageHomeControllerAuthorizeStatusPage { get; set; }
        public string LoggerErrorMessageOAuthControllerSlackDetailsAdd { get; set; }
        public string PreviousDayStatus { get; set; }
        public string PreviousDayScrumAnswer { get; set; }
        public string InActiveProjectDetailsFromOauthInActiveUser { get; set; }
        public string NameFormat { get; set; }
        public string AnswerNotRecorded { get; set; }
        public string UserNotInOAuthOrProject { get; set; }
        public string ScrumBotToken { get; set; }
        public string ScrumBotName { get; set; }
        public string LoggerScrumBot { get; set; }
        public string LoggerTaskMailBot { get; set; }
        public string ScrumLaterDone { get; set; }
        public string AlreadyAnswered { get; set; }
        public string NotExpected { get; set; }
        public string ScrumIsHalted { get; set; }
        public string NoSlackDetails { get; set; }
        public string ScrumCannotBeHalted { get; set; }
        public string ScrumCannotBeResumed { get; set; }
        public string ProjectDetailsFromOauthInActiveUser { get; set; }
        public string ProjectInActive { get; set; }
        public string ScrumInProgress { get; set; }
        public string EmployeesListFromOauthThreeEmployeesInActive { get; set; }
        public string SlackUserNotFound { get; set; }
        public string UserNotInSlack { get; set; }
        public string NotInSlackOrNotExpectedUser { get; set; }

        public string InValidStartCommand { get; set; }
        public string InActiveEmployeesList { get; set; }
        public string EmployeesListFromOauthOneEmployee { get; set; }
        public string EmployeesListFromOauthThreeEmployees { get; set; }
        public string ThirdUserSlackUserId { get; set; }
        public string UserNotInProject { get; set; }
        public string NoQuestion { get; set; }
        public string NoEmployeeFound { get; set; }
        public string MarkedInActive { get; set; }
        public string Unrecognized { get; set; }
        public string UserChange { get; set; }
        public string ChannelCreated { get; set; }
        public string ChannelArchive { get; set; }
        public string GroupArchive { get; set; }
        public string ChannelRename { get; set; }
        public string GroupRename { get; set; }
        public string ListLinks { get; set; }

        public string NoProjectFound { get; set; }
        public string ScrumComplete { get; set; }
        public string ScrumNotStarted { get; set; }
        public string ScrumAlreadyConducted { get; set; }
        public string GoodDay { get; set; }
        public string Time { get; set; }
        public string PleaseAnswer { get; set; }
        public string AllAnswerRecorded { get; set; }
        public string NotLaterYet { get; set; }
        public string SendTaskMailConfirmationErrorMessage { get; set; }
        public string RequestToStartTaskMail { get; set; }
        public string AlreadyMailSend { get; set; }
        public string TaskMailSubject { get; set; }
        public string FirstNameForTest { get; set; }
        public string AccessTokenForTest { get; set; }
        public string EmailForTest { get; set; }
        public string StringIdForTest { get; set; }
        public string LastNameForTest { get; set; }
        public string UserDetailsFromOauthServer { get; set; }
        public string SlashCommandText { get; set; }
        public string PromactStringName { get; set; }
        public string FirstQuestionForTest { get; set; }
        public string TeamLeaderDetailsFromOauthServer { get; set; }
        public string CommentAndDescriptionForTest { get; set; }
        public string ManagementDetailsFromOauthServer { get; set; }
        public string TaskMailReport { get; set; }
        public string ListOfEmployeeForTeamLeader { get; set; }
        public string EmployeeInformation { get; set; }
        public string TaskMailReportTeamLeader { get; set; }
        public string TeamLeaderEmailForTest { get; set; }
        public string ManagementFirstForTest { get; set; }
        public string ManagementEmailForTest { get; set; }
        public string LeaveReasonForTest { get; set; }
        public string LeaveTypeForTest { get; set; }
        public string ChannelId { get; set; }
        public string ChannelName { get; set; }
        public string ChannelAddInstruction { get; set; }
        public string ProjectNotInOAuth { get; set; }
        public string GroupNameStartsWith { get; set; }
        public string OnlyPrivateChannel { get; set; }
        public string ChannelAddSuccess { get; set; }
        public string Add { get; set; }
        public string Channel { get; set; }
        public string Command { get; set; }
        public string ResponseUrl { get; set; }
        public string TeamDomain { get; set; }
        public string OAuthProjName { get; set; }
        public string TeamId { get; set; }
        public string Text { get; set; }
        public string Token { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string LeaveBot { get; set; }
        public string UnderConstruction { get; set; }
        public string Hello { get; set; }
        public string All { get; set; }
        public string LinkTest { get; set; }
        public string LinkChannelNoName { get; set; }
        public string UnlinkCommand { get; set; }
        public string UnlinkTest { get; set; }
        public string ProjectTeamLeaderInActiveDetail { get; set; }
        public string OAuthProjectName { get; set; }
        public string InActiveProjectTeamLeaderDetail { get; set; }
        public string StringHourForTest { get; set; }
        public string AfterLogIn { get; set; }
        public string Home { get; set; }
        public string Index { get; set; }
        public string WebConfig { get; set; }
        public string MailSetting { get; set; }
        public string SlackChatUpdateUrl { get; set; }
        public string ProjectUserUrl { get; set; }
        public string ProjectUrl { get; set; }
        public string UserUrl { get; set; }
        public string OAuthUrl { get; set; }
        public string ClientReturnUrl { get; set; }
        public string LeaveManagementAuthorizationUrl { get; set; }
        public string ChatPostUrl { get; set; }
        public string SlashCommandLeaveListErrorMessage { get; set; }
        public string SlashCommandLeaveCancelErrorMessage { get; set; }
        public string SlashCommandLeaveStatusErrorMessage { get; set; }
        public string Host { get; set; }
        public string Port { get; set; }
        public string TokenEmpty { get; set; }
        public string ErrorMsg { get; set; }
        public string ErrorMsgNewPrivateChannel { get; set; }
        public string MailUserName { get; set; }
        public string Password { get; set; }
        public string EnableSsl { get; set; }
        public string IncomingWebHookUrl { get; set; }
        public string TaskmailAccessToken { get; set; }
        public string SlackOAuthClientId { get; set; }
        public string SlackOAuthClientSecret { get; set; }
        public string PromactOAuthClientId { get; set; }
        public string PromactOAuthClientSecret { get; set; }
        public string LoggerErrorMessageLeaveRequestControllerSlackRequest { get; set; }
        public string LoggerErrorMessageLeaveRequestControllerSlackButtonRequest { get; set; }
        public string LoggerErrorMessageHomeControllerExtrenalLogin { get; set; }
        public string LoggerErrorMessageHomeControllerSlackOAuthAuthorization { get; set; }
        public string LoggerErrorMessageHomeControllerExtrenalLoginCallBack { get; set; }
        public string LoggerErrorMessageHomeControllerLogoff { get; set; }
        public string LoggerErrorMessageOAuthControllerRefreshToken { get; set; }
        public string LoggerErrorMessageOAuthControllerSlackOAuth { get; set; }
        public string LoggerErrorMessageOAuthControllerSlackEvent { get; set; }
        public string LoggerErrorMessageTaskMailBot { get; set; }
        public string SlackBotName { get; set; }
        public string CasualLeaveUrl { get; set; }
        public string CasualLeaveResponse { get; set; }
        public string SlackChannelIdForTest { get; set; }
        public string MessageTsForTest { get; set; }
        public string SorryYouCannotApplyLeave { get; set; }
        public string LeaveListCommandForTest { get; set; }
        public string LeaveCancelCommandForTest { get; set; }
        public string Cancel { get; set; }
        public string FalseStringNameForTest { get; set; }
        public string LeaveNoUserErrorMessage { get; set; }
        public string LeaveBalanceReplyTextForTest { get; set; }
        public string OrElseString { get; set; }
        public string Admin { get; set; }
        public string Employee { get; set; }
        public string TeamLeader { get; set; }
        public string EmptyString { get; set; }
        public string VerificationUrl { get; set; }
        public string TeamJoin { get; set; }
        public string SlackOAuthResponseText { get; set; }
        public string AccessTokenSlack { get; set; }
        public string UserDetailsResponseText { get; set; }
        public string ChannelDetailsResponseText { get; set; }
        public string GroupDetailsResponseText { get; set; }
        public string List { get; set; }
        public string WrongLeaveCancelCommandForTest { get; set; }
        public string LeaveStatusTestForOwn { get; set; }
        public string SecondQuestionForTest { get; set; }
        public string ThirdQuestionForTest { get; set; }
        public string ForthQuestionForTest { get; set; }
        public string FifthQuestionForTest { get; set; }
        public string SixthQuestionForTest { get; set; }
        public string SeventhQuestionForTest { get; set; }
        public string YouAreNotInExistInOAuthServer { get; set; }
        public string HourSpentForTest { get; set; }
        public string StatusOfWorkForTest { get; set; }
        public string SendEmailYesForTest { get; set; }
        public string SendEmailNoForTest { get; set; }
        public string NotTypeOfLeave { get; set; }
        public string DateFormatErrorMessage { get; set; }
        public string ErrorWhileSendingEmail { get; set; }
        public string UserIsAdmin { get; set; }
        public string LeaveDoesnotExist { get; set; }
        public string AdminErrorMessageUpdateSickLeave { get; set; }
        public string True { get; set; }
        public string LeaveStatusCommandForTest { get; set; }
        public string LeaveBalanceTestForOwn { get; set; }
        public string LeaveHelpTestForOwn { get; set; }
        public string LeaveBalanceSickReplyTextForTest { get; set; }
        public string SlashCommandTextSick { get; set; }
        public string SlashCommandTextSickForUser { get; set; }
        public string NameForTest { get; set; }
        public string RequestToEnterProperAction { get; set; }
        public string SlashCommandTextErrorLeaveType { get; set; }
        public string SlashCommandTextErrorDateFormatSick { get; set; }
        public string SlashCommandTextErrorDateFormatCasual { get; set; }
        public string SlashCommandTextCasual { get; set; }
        public string SlashCommandUpdate { get; set; }
        public string SlashCommandUpdateDateError { get; set; }
        public string SlashCommandUpdateWrongId { get; set; }
        public string SickLeaveDoesnotExist { get; set; }
        public string UpdateEnterAValidLeaveId { get; set; }
        public string SlashCommandUpdateInValidId { get; set; }
        public string ErrorOfEmailServiceFailureTaskMail { get; set; }
        public string AdminErrorMessageApplySickLeave { get; set; }
        public string UserNotFound { get; set; }
        public string BotNotFound { get; set; }
        public string PersonNotAvailable { get; set; }
        public string FormatForDate { get; set; }
        public string ScrumFirstQuestion { get; set; }
        public string ScrumSecondQuestion { get; set; }
        public string ScrumThirdQuestion { get; set; }
        public string AllProjectUrl { get; set; }
        public string GetProjectDetails { get; set; }
        public string Start { get; set; }

        #region String Constants for Test Cases

        public string InActiveProjectDetailsFromOauth { get; set; }
        public string UserNameForTest { get; set; }
        public string GroupName { get; set; }
        public string AnswerStatement { get; set; }
        public string ChannelIdForTest { get; set; }
        public string PhoneForTest { get; set; }
        public string ScrumQuestionForTest { get; set; }
        public string ChannelNameForTest { get; set; }
        public string ProjectDetailsFromOauth { get; set; }
        public string EmployeeDetailsFromOauth { get; set; }
        public string EmployeesListFromOauth { get; set; }
        public string UserBySlackUserName { get; set; }
        public string UserBySlackUserNameForLeaveApplicant { get; set; }
        public string UserIdForTest { get; set; }
        public string TestUser { get; set; }
        public string scrumAnswerForTest { get; set; }
        int ProjectIdForTest { get; set; }
        public string Halt { get; set; }
        public string Resume { get; set; }
        public string AlreadyMarkedAsAnswered { get; set; }
        public string TeamLeaderIdForTest { get; set; }
        public string EmployeeIdForTest { get; set; }
        public string TestAccessToken { get; set; }
        public string TestUserName { get; set; }
        public string TestUserNameFalse { get; set; }
        public string FirstUserName { get; set; }
        public string FirstUserNameFalse { get; set; }
        public string ProjectUsers { get; set; }
        public string TeamLeaderDetailFromOauthServer { get; set; }
        public string EmployeeDetailFromOauthServer { get; set; }
        public string IdForTest { get; set; }
        public string TestUserId { get; set; }
        public string NextQuestion { get; set; }
        public string QuestionToNextEmployee { get; set; }
        public string PreviousDayStatusForTest { get; set; }
        public string AdminLogin { get; set; }
        public string TeamLeaderLogin { get; set; }
        public string EmployeeLogin { get; set; }
        public string TeamLeaderLoginDetails { get; set; }
        public string ProjectDetail { get; set; }
        public string ProjectDetailsForAdminFromOauth { get; set; }
        public string ProjectDetailsForTeamLeaderFromOauth { get; set; }
        public string ProjectDetailsForEmployeeFromOauth { get; set; }
        public string TestAnswer { get; set; }
        public string TestId { get; set; }
        public string TestGroupName { get; set; }
        public string TestQuestion { get; set; }
        public string EmployeesListFromOauthInValid { get; set; }
        public string UnExpectedInActiveUser { get; set; }
        public string EmployeesListInValid { get; set; }
        public string InActiveInOAuth { get; set; }
        public string OAuthUserDetails { get; set; }
        public string InValidOAuthUsers { get; set; }
        public string WrongActionSlashCommand { get; set; }
        public string LeaveWrongCommandForBackDateCL { get; set; }
        public string LeaveWrongCommandForBeyondDateFirstExample { get; set; }
        public string LeaveWrongCommandForBeyondDateSecondExample { get; set; }
        public string LeaveWrongCommandForBackDateSL { get; set; }
        public string SlashCommandUpdateForBeyondStartDateFirstExample { get; set; }
        public string SlashCommandUpdateForBeyondStartDateSecondExample { get; set; }
        public string LeaveCommand { get; set; }

        #endregion

        public string RoleAdmin { get; set; }
        public string RoleTeamLeader { get; set; }
        public string RoleEmployee { get; set; }

        public string TeamMembersUrl { get; set; }
        public string UserRoleUrl { get; set; }

        public string NotAvailable { get; set; }
        public string NextPage { get; set; }
        public string Previouspage { get; set; }
        public string HourLimitExceed { get; set; }
        public string StartWorking { get; set; }
        public string HourSpentForTesting { get; set; }
        public string HourSpentExceeded { get; set; }
        public string BackDateErrorMessage { get; set; }
        public string InValidDateErrorMessage { get; set; }
        public string JsonContentString { get; set; }
        public string UserSlackId { get; set; }
        public string TeamLeaderSlackId { get; set; }
        public string ManagementSlackId { get; set; }
        public string Ok { get; set; }
        public string LeaveAllowed { get; set; }
        public string LeaveAlreadyExistOnSameDate { get; set; }
        public string ReplyTextForUpdateLeave { get; set; }
        public string ReplyTextForCasualLeaveList { get; set; }
        public string ReplyTextForSickLeaveList { get; set; }
        public string ReplyTextForCancelLeave { get; set; }
        public string ReplyTextForErrorInCancelLeave { get; set; }
        public string ReplyTextForCasualLeaveStatus { get; set; }
        public string ReplyTextForSickLeaveStatus { get; set; }
        public string ReplyTextForCasualLeaveBalance { get; set; }
        public string ReplyTextForSickLeaveBalance { get; set; }
        public string ReplyTextForSickLeaveUpdate { get; set; }
        public string ReplyTextForSMTPExceptionErrorMessage { get; set; }
        public string SlashCommandErrorMessage { get; set; }
        public string ReplyTextForCasualLeaveApplied { get; set; }
        public string ReplyTextForSickLeaveApplied { get; set; }
        public string UpdateMessageUrl { get; set; }
        public string AtTheRate { get; set; }
        public string SlackOauthRequestUrl { get; set; }
        public string SlackUserDetailsUrl { get; set; }
        public string EmployeeFirstLastNameFormat { get; set; }
        public string FirstAndSecondIndexStringFormat { get; set; }
        public string FirstSecondAndThirdIndexStringFormat { get; set; }
        public string StringValueOneForTest { get; set; }
        public string StringValueFiftyFiveForTest { get; set; }
        public string ControllerErrorMessageStringFormat { get; set; }
        public string ExternalLoginUrl { get; set; }
        public string SlackAuthorizeAction { get; set; }
        public string Default { get; set; }
        public string CasualLeaveUpdateMessageForUser { get; set; }
        public string AlreadyUpdatedMessage { get; set; }
        public string LeaveUpdateResponseJsonString { get; set; }
        public string Payload { get; set; }
        public string LeaveUpdateEmailStringFormat { get; set; }
        public string RequestToAddSlackApp { get; set; }
        public string Star { get; set; }
        public string HttpRequestExceptionErrorMessage { get; set; }
        public string Space { get; set; }
        public string UserDetailsFromOauthServerFalse { get; set; }
        public string TaskMailMaximumTime { get; set; }
        public string Scopes { get; set; }
        public string AuthenticationType { get; set; }
        public string AuthenticationTypeOidc { get; set; }
        public string ResponseType { get; set; }
        public string Scope { get; set; }
        public string RedirectUrl { get; set; }
        public string Sub { get; set; }
        public string Email { get; set; }
        public string SlackUserID { get; set; }
        public string RoleClaimType { get; set; }
        public string NameClaimType { get; set; }
        public string Bearer { get; set; }
        public string TaskModule { get; set; }
        public string ScrumModule { get; set; }
        public string LeaveModule { get; set; }
        public string Management { get; set; }
        public string TestEmail { get; set; }
        public string SecondTestEmail { get; set; }
        public string TeamLeaderGroup { get; set; }
        public string ManagementGroup { get; set; }
        public string TeamMembersGroup { get; set; }
        public string EmailListForGroup { get; set; }
        public string DetailsAndSlashForUrl { get; set; }
        public string UserDetailsNotFound { get; set; }

        #region Redmine
        public string RedmineBaseUrl { get; set; }
        public string RequestToEnterProperRedmineAction { get; set; }
        public string RedmineHelp { get; set; }
        public string RedmineApiKey { get; set; }
        public string RedmineProjectListAssignToMeUrl { get; set; }
        public string NoProjectFoundForUser { get; set; }
        public string ProperRedmineIssueAction { get; set; }
        public string ProperProjectId { get; set; }
        public string RedmineIssueListAssignToMeByProjectIdUrl { get; set; }
        public string ProjectDoesNotExistForThisId { get; set; }
        public string ErrorInCreatingIssue { get; set; }
        public string JsonApplication { get; set; }
        public string IssueSuccessfullyCreatedMessage { get; set; }
        public string RedmineIssueUrl { get; set; }
        public string NoUserFoundInProject { get; set; }
        public string IssueDoesNotExist { get; set; }
        public string IssueDetailsUrl { get; set; }
        public string RedmineIssueUpdateUrl { get; set; }
        public string IssueUrl { get; set; }
        public string ErrorInUpdateIssue { get; set; }
        public string IssueSuccessfullUpdated { get; set; }
        public string TimeEntryUrl { get; set; }
        public string HourIsNotNumericMessage { get; set; }
        public string TimeEntryActivityErrorMessage { get; set; }
        public string TimeEnrtyAddSuccessfully { get; set; }
        public string ErrorInAddingTimeEntry { get; set; }
        public string RedmineIssueMessageFormat { get; set; }
        public string RedminePriorityErrorMessage { get; set; }
        public string RedmineStatusErrorMessage { get; set; }
        public string RedmineTrackerErrorMessage { get; set; }
        public string UserByProjectIdUrl { get; set; }
        public string RedmineTimeEntryDateFormat { get; set; }
        public string RedmineWrongActionCommand { get; set; }
        public string RedmineCommandProjectList { get; set; }
        public string RedmineWrongIssueActionCommand { get; set; }
        public string RedmineCommandIssueListWrongProjectId { get; set; }
        public string RedmineCommandIssueList { get; set; }
        public string RedmineCommandCreateWrongPriority { get; set; }
        public string RedmineCommandCreateWrongStatus { get; set; }
        public string RedmineCommandCreateWrongTracker { get; set; }
        public string RedmineCommandCreateWrongProjectId { get; set; }
        public string RedmineCommandCreate { get; set; }
        public string RedmineCommandChangeAssign { get; set; }
        public string RedmineCommandIssueClose { get; set; }
        public string RedmineTimeEntryWrongIssueId { get; set; }
        public string RedmineTimeEntry { get; set; }
        public string RedmineTimeEntryHourFormatCommand { get; set; }
        public string RedmineTimeEntryDateFormatCommand { get; set; }
        public string RedmineTimeEntryTimeEntryActivityFormatCommand { get; set; }
        public string RedmineCommandHelp { get; set; }
        public string RedmineApiKeyIsNull { get; set; }
        public string RedmineKeyAddSuccessfully { get; set; }
        public string PleaseEnterValidAPIKey { get; set; }
        public string RedmineAPIKeyCommand { get; set; }
        public string RedmineProjectListFormat { get; set; }
        #endregion

        public string TaskMailRestartSuggestionMessage { get; set; }
    }
}
